// <auto-generated />
using System;
using Gestion_EDT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gestion_EDT.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260607222433_AjoutColonneSemaine")]
    partial class AjoutColonneSemaine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gestion_EDT.Models.Batiment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("nom_batiment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Batiments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            nom_batiment = "Bâtiment A"
                        },
                        new
                        {
                            Id = 2,
                            nom_batiment = "Bâtiment B"
                        },
                        new
                        {
                            Id = 3,
                            nom_batiment = "Bâtiment C"
                        });
                });

            modelBuilder.Entity("Gestion_EDT.Models.Cycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MentionId")
                        .HasColumnType("int");

                    b.Property<string>("niveau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nom_cycle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MentionId");

                    b.ToTable("Cycles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MentionId = 1,
                            niveau = "L",
                            nom_cycle = "Licence Informatique"
                        },
                        new
                        {
                            Id = 2,
                            MentionId = 1,
                            niveau = "M",
                            nom_cycle = "Master Informatique"
                        },
                        new
                        {
                            Id = 3,
                            MentionId = 2,
                            niveau = "L",
                            nom_cycle = "Licence Management"
                        },
                        new
                        {
                            Id = 4,
                            MentionId = 2,
                            niveau = "M",
                            nom_cycle = "Master Management"
                        },
                        new
                        {
                            Id = 5,
                            MentionId = 3,
                            niveau = "L",
                            nom_cycle = "Licence ICM"
                        },
                        new
                        {
                            Id = 6,
                            MentionId = 3,
                            niveau = "M",
                            nom_cycle = "Master ICM"
                        });
                });

            modelBuilder.Entity("Gestion_EDT.Models.Enseignant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("matricule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nom_enseignant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prenom_enseignant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Enseignants");
                });

            modelBuilder.Entity("Gestion_EDT.Models.Groupe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ParcoursId")
                        .HasColumnType("int");

                    b.Property<string>("code_groupe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nb_etudiant")
                        .HasColumnType("int");

                    b.Property<string>("nom_groupe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParcoursId");

                    b.ToTable("Groupes", t =>
                        {
                            t.HasCheckConstraint("CHK_Groupe_NbEtudiant", "nb_etudiant > 0");
                        });
                });

            modelBuilder.Entity("Gestion_EDT.Models.Matiere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("code_mat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("intitule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nb_heure")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Matieres");
                });

            modelBuilder.Entity("Gestion_EDT.Models.Mention", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("code_mention")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nom_mention")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Mentions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            code_mention = "INFO",
                            nom_mention = "Informatique"
                        },
                        new
                        {
                            Id = 2,
                            code_mention = "MGT",
                            nom_mention = "Management"
                        },
                        new
                        {
                            Id = 3,
                            code_mention = "ICM",
                            nom_mention = "Information, Communication et Multimédia"
                        });
                });

            modelBuilder.Entity("Gestion_EDT.Models.Parcours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CycleId")
                        .HasColumnType("int");

                    b.Property<string>("nom_parcours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CycleId");

                    b.ToTable("Parcours");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CycleId = 1,
                            nom_parcours = "L1"
                        },
                        new
                        {
                            Id = 2,
                            CycleId = 1,
                            nom_parcours = "L2"
                        },
                        new
                        {
                            Id = 3,
                            CycleId = 1,
                            nom_parcours = "L3"
                        },
                        new
                        {
                            Id = 4,
                            CycleId = 2,
                            nom_parcours = "M1"
                        },
                        new
                        {
                            Id = 5,
                            CycleId = 2,
                            nom_parcours = "M2"
                        },
                        new
                        {
                            Id = 6,
                            CycleId = 3,
                            nom_parcours = "L1"
                        },
                        new
                        {
                            Id = 7,
                            CycleId = 3,
                            nom_parcours = "L2"
                        },
                        new
                        {
                            Id = 8,
                            CycleId = 3,
                            nom_parcours = "L3"
                        },
                        new
                        {
                            Id = 9,
                            CycleId = 4,
                            nom_parcours = "M1"
                        },
                        new
                        {
                            Id = 10,
                            CycleId = 4,
                            nom_parcours = "M2"
                        },
                        new
                        {
                            Id = 11,
                            CycleId = 5,
                            nom_parcours = "L1"
                        },
                        new
                        {
                            Id = 12,
                            CycleId = 5,
                            nom_parcours = "L2"
                        },
                        new
                        {
                            Id = 13,
                            CycleId = 5,
                            nom_parcours = "L3"
                        },
                        new
                        {
                            Id = 14,
                            CycleId = 6,
                            nom_parcours = "M1"
                        },
                        new
                        {
                            Id = 15,
                            CycleId = 6,
                            nom_parcours = "M2"
                        });
                });

            modelBuilder.Entity("Gestion_EDT.Models.Salle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatimentId")
                        .HasColumnType("int");

                    b.Property<int>("capacite")
                        .HasColumnType("int");

                    b.Property<string>("num_salle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BatimentId");

                    b.ToTable("Salles", t =>
                        {
                            t.HasCheckConstraint("CHK_Salle_Capacite", "capacite > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BatimentId = 1,
                            capacite = 40,
                            num_salle = "A101"
                        },
                        new
                        {
                            Id = 2,
                            BatimentId = 1,
                            capacite = 40,
                            num_salle = "A102"
                        },
                        new
                        {
                            Id = 3,
                            BatimentId = 2,
                            capacite = 30,
                            num_salle = "LABO"
                        },
                        new
                        {
                            Id = 4,
                            BatimentId = 3,
                            capacite = 200,
                            num_salle = "AMP1"
                        });
                });

            modelBuilder.Entity("Gestion_EDT.Models.Seance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EnseignantId")
                        .HasColumnType("int");

                    b.Property<int>("GroupeId")
                        .HasColumnType("int");

                    b.Property<int>("MatiereId")
                        .HasColumnType("int");

                    b.Property<int>("SalleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("date_seance")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("heure_debut")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("heure_fin")
                        .HasColumnType("time");

                    b.Property<int>("semaine")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupeId");

                    b.HasIndex("MatiereId");

                    b.HasIndex("semaine")
                        .HasDatabaseName("IDX_Seance_Semaine");

                    b.HasIndex("EnseignantId", "date_seance")
                        .HasDatabaseName("IDX_Seance_Enseignant_Date");

                    b.HasIndex("SalleId", "date_seance")
                        .HasDatabaseName("IDX_Seance_Salle_Date");

                    b.ToTable("Seances", t =>
                        {
                            t.HasCheckConstraint("CHK_Seance_Heures", "heure_fin > heure_debut");

                            t.HasCheckConstraint("CHK_Seance_Semaine", "semaine BETWEEN 1 AND 52");
                        });
                });

            modelBuilder.Entity("Gestion_EDT.Models.Cycle", b =>
                {
                    b.HasOne("Gestion_EDT.Models.Mention", "Mention")
                        .WithMany("Cycles")
                        .HasForeignKey("MentionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mention");
                });

            modelBuilder.Entity("Gestion_EDT.Models.Groupe", b =>
                {
                    b.HasOne("Gestion_EDT.Models.Parcours", "Parcours")
                        .WithMany("Groupes")
                        .HasForeignKey("ParcoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parcours");
                });

            modelBuilder.Entity("Gestion_EDT.Models.Parcours", b =>
                {
                    b.HasOne("Gestion_EDT.Models.Cycle", "Cycle")
                        .WithMany("Parcours")
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cycle");
                });

            modelBuilder.Entity("Gestion_EDT.Models.Salle", b =>
                {
                    b.HasOne("Gestion_EDT.Models.Batiment", "Batiment")
                        .WithMany("Salles")
                        .HasForeignKey("BatimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batiment");
                });

            modelBuilder.Entity("Gestion_EDT.Models.Seance", b =>
                {
                    b.HasOne("Gestion_EDT.Models.Enseignant", "Enseignant")
                        .WithMany("Seances")
                        .HasForeignKey("EnseignantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestion_EDT.Models.Groupe", "Groupe")
                        .WithMany("Seances")
                        .HasForeignKey("GroupeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestion_EDT.Models.Matiere", "Matiere")
                        .WithMany("Seances")
                        .HasForeignKey("MatiereId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestion_EDT.Models.Salle", "Salle")
                        .WithMany("Seances")
                        .HasForeignKey("SalleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enseignant");

                    b.Navigation("Groupe");

                    b.Navigation("Matiere");

                    b.Navigation("Salle");
                });

            modelBuilder.Entity("Gestion_EDT.Models.Batiment", b =>
                {
                    b.Navigation("Salles");
                });

            modelBuilder.Entity("Gestion_EDT.Models.Cycle", b =>
                {
                    b.Navigation("Parcours");
                });

            modelBuilder.Entity("Gestion_EDT.Models.Enseignant", b =>
                {
                    b.Navigation("Seances");
                });

            modelBuilder.Entity("Gestion_EDT.Models.Groupe", b =>
                {
                    b.Navigation("Seances");
                });

            modelBuilder.Entity("Gestion_EDT.Models.Matiere", b =>
                {
                    b.Navigation("Seances");
                });

            modelBuilder.Entity("Gestion_EDT.Models.Mention", b =>
                {
                    b.Navigation("Cycles");
                });

            modelBuilder.Entity("Gestion_EDT.Models.Parcours", b =>
                {
                    b.Navigation("Groupes");
                });

            modelBuilder.Entity("Gestion_EDT.Models.Salle", b =>
                {
                    b.Navigation("Seances");
                });
#pragma warning restore 612, 618
        }
    }
}
